language: ruby
rvm:
- 2.6.3
node_js:
- 8.9.4
services:
- postgresql
addons:
  postgresql: "9.6"
before_install:
- gem update --system
- gem install bundler
before_script:
- createuser ranked
- createdb -O ranked ranked_test
- yarn install
- bundle exec rails db:migrate
- bundle exec rails webpacker:compile
env:
  secure: 2iVzVROWwsYS9bLCYSWiRKa9uFp4LsfSRpg63o/9KpPAI+hY2H3wkxGC9bVbd8yq1RVO1sdnYNApH4bi8RUiv8Ho0mosKN2Ucn5w2AMBjKHtah4wkSlfoJSWPd326zCb1GQzZcQ/lXmtAMV8Fgkw2QpB8qcorsmPnK6bpvaGDwyFuqmZ3FWedbi1B2oB5OPjzzFDT+7nePir0dywGUvrY8y2AdyWZ9LJZwlANyDG2dy1+vRKtJBMbJGAn1htfFZBKCO41Usn/vIL7aFYWYV+WBF4gQuOr2cMG6DD26cJbDfKad5kHx9MgaN8eopirPKSufAYNHgtzbQUfWOgZqAL3PLm4hG1J512S4dIoHUOuC6huEN4jqJU3HuP+HA54vThjg2hmzID1sJZ/+sUV+PAgxGiMeC7ZU0PI09nphkmBVL7hm4s+mHhYCnwXc1YtCHeJjqzloqjU64HTavfuBTfAVXbUprJVEZVp4Jhb+b9k0S2wJ8tWdMvQbLOZDQ86o/WxveK6SQk00sYTL7wsaEsylTiN7TdnCS5XRuxsbtvig7hUyATPXIub8l3KERQbcqkIkRG4gQerwzcMTLa08DpadngtKtIAqk9HTi6VGvkbF821C88kGZHxY4VYKLr791RJUD2OuE1S5iJS0cdQdGcr8R8bAZj/0po7/YI9p3yKRQ=
