language: ruby
rvm:
- 2.6.1
postgres:
  adapter: postgresql
  database: ranked_test
  username: ranked
before_script:
- createuser ranked
- createdb -O ranked ranked_test
- gem update --system
- gem install bundler
- "bundle exec rake db:migrate"
