language: ruby
rvm:
- 2.5.0
postgres:
  adapter: postgresql
  database: ranked_test
  username: ranked
before_script:
- createuser ranked
- createdb -O ranked ranked_test
- "bundle exec rake db:migrate"
