# PostgreSQL. Versions 9.1 and up are supported.
#
#
shared:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: ranked

development:
  database: ranked_development

test:
  database: ranked_test

production:
  database: ranked_production
  password: <%= ENV['RANKED_DATABASE_PASSWORD'] %>
